/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareGuideRouteImport } from './routes/care-guide'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GiftCardsRouteImport } from './routes/gift-cards'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StyleQuizRouteImport } from './routes/style-quiz'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as WardrobeStudioRouteImport } from './routes/wardrobe-studio'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareGuideRoute = CareGuideRouteImport.update({
  id: '/care-guide',
  path: '/care-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsRoute = GiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleQuizRoute = StyleQuizRouteImport.update({
  id: '/style-quiz',
  path: '/style-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const WardrobeStudioRoute = WardrobeStudioRouteImport.update({
  id: '/wardrobe-studio',
  path: '/wardrobe-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-guide': typeof CareGuideRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gift-cards': typeof GiftCardsRoute
  '/lookbook': typeof LookbookRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/style-quiz': typeof StyleQuizRoute
  '/sustainability': typeof SustainabilityRoute
  '/track-order': typeof TrackOrderRoute
  '/wardrobe-studio': typeof WardrobeStudioRoute
  '/wishlist': typeof WishlistRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-guide': typeof CareGuideRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gift-cards': typeof GiftCardsRoute
  '/lookbook': typeof LookbookRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/style-quiz': typeof StyleQuizRoute
  '/sustainability': typeof SustainabilityRoute
  '/track-order': typeof TrackOrderRoute
  '/wardrobe-studio': typeof WardrobeStudioRoute
  '/wishlist': typeof WishlistRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-guide': typeof CareGuideRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gift-cards': typeof GiftCardsRoute
  '/lookbook': typeof LookbookRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/style-quiz': typeof StyleQuizRoute
  '/sustainability': typeof SustainabilityRoute
  '/track-order': typeof TrackOrderRoute
  '/wardrobe-studio': typeof WardrobeStudioRoute
  '/wishlist': typeof WishlistRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/care-guide'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/gift-cards'
    | '/lookbook'
    | '/rewards'
    | '/shop'
    | '/style-quiz'
    | '/sustainability'
    | '/track-order'
    | '/wardrobe-studio'
    | '/wishlist'
    | '/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/care-guide'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/gift-cards'
    | '/lookbook'
    | '/rewards'
    | '/shop'
    | '/style-quiz'
    | '/sustainability'
    | '/track-order'
    | '/wardrobe-studio'
    | '/wishlist'
    | '/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/care-guide'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/gift-cards'
    | '/lookbook'
    | '/rewards'
    | '/shop'
    | '/style-quiz'
    | '/sustainability'
    | '/track-order'
    | '/wardrobe-studio'
    | '/wishlist'
    | '/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareGuideRoute: typeof CareGuideRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  GiftCardsRoute: typeof GiftCardsRoute
  LookbookRoute: typeof LookbookRoute
  RewardsRoute: typeof RewardsRoute
  ShopRoute: typeof ShopRoute
  StyleQuizRoute: typeof StyleQuizRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WardrobeStudioRoute: typeof WardrobeStudioRoute
  WishlistRoute: typeof WishlistRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-guide': {
      id: '/care-guide'
      path: '/care-guide'
      fullPath: '/care-guide'
      preLoaderRoute: typeof CareGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards': {
      id: '/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof GiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-quiz': {
      id: '/style-quiz'
      path: '/style-quiz'
      fullPath: '/style-quiz'
      preLoaderRoute: typeof StyleQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wardrobe-studio': {
      id: '/wardrobe-studio'
      path: '/wardrobe-studio'
      fullPath: '/wardrobe-studio'
      preLoaderRoute: typeof WardrobeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareGuideRoute: CareGuideRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  GiftCardsRoute: GiftCardsRoute,
  LookbookRoute: LookbookRoute,
  RewardsRoute: RewardsRoute,
  ShopRoute: ShopRoute,
  StyleQuizRoute: StyleQuizRoute,
  SustainabilityRoute: SustainabilityRoute,
  TrackOrderRoute: TrackOrderRoute,
  WardrobeStudioRoute: WardrobeStudioRoute,
  WishlistRoute: WishlistRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
